# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-18 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(blank=True, max_length=100)),
                ('title', models.CharField(blank=True, max_length=15)),
            ],
        ),
    ]
